_BASE_CONFIG_: configs/model_configs/ablation_a3_radar7pillar_vel_decode_tuned.yaml

DATA_CONFIG:
  DATA_AUGMENTOR:
    DISABLE_AUG_LIST: [gt_sampling]
    AUG_CONFIG_LIST:
      - NAME: gt_sampling
        USE_ROAD_PLANE: False
        DB_INFO_PATH: [vod_radar_dbinfos_train.pkl]
        PREPARE:
          filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5']
        SAMPLE_GROUPS: ['Car:10', 'Pedestrian:10', 'Cyclist:10']
        NUM_POINT_FEATURES: 7
        DATABASE_WITH_FAKELIDAR: False
        REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
        LIMIT_WHOLE_SCENE: True
      - NAME: random_world_flip
        ALONG_AXIS_LIST: ['x']
      - NAME: random_world_scaling
        WORLD_SCALE_RANGE: [0.92, 1.08]
      - NAME: random_world_rotation
        WORLD_ROT_ANGLE: [-0.15, 0.15]

OPTIMIZATION:
  NUM_EPOCHS: 36
  BATCH_SIZE_PER_GPU: 2
  LR: 0.0025
  PCT_START: 0.35
